### ISSUE TITLE
Documentation: API Key Auth Example

### ISSUE THREAD

**Issue by michaeltlombardi** [cloudsmith-io/cloudsmith-api-go#3]
As an app developer looking to integrate my app with Cloudsmith, I would like to be able to reference an example in addition to instructions for authorizing API calls with a key to ease my development.

There is an existing example for using basic authentication, but not an API key.

**Comment by chrisimcevoy** [comment]
Hi @michaeltlombardi ,

Please accept my apologies for the late response on this issue.

I believe the example you were looking for was added in #2 which was merged the same day this issue was created.

Do come back to us if the api key example currently in README.md hasn't resolved this for you.

**Comment by michaeltlombardi** [comment]
Hi, @chrisimcevoy! Unless I'm misunderstanding, the example [currently in the readme](https://github.com/cloudsmith-io/cloudsmith-api-go#documentation-for-authorization) shows using basic auth for the operation.

**Comment by chrisimcevoy** [comment]
Ah, I see what you mean now. Apologies!

I'll look into this for you as soon as possible :)
